draft-ietf-openpgp-pqc.xml: test-vectors/v6-eddsa-sample-sk.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v6-eddsa-sample-pk.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v6-eddsa-sample-message.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v4-eddsa-sample-sk.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v4-eddsa-sample-pk.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v4-eddsa-sample-message.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v6-mldsa-65-sample-sk.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v6-mldsa-65-sample-pk.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v6-mldsa-65-sample-message.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v6-mldsa-65-sample-signature.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v6-mldsa-87-sample-sk.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v6-mldsa-87-sample-pk.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v6-mldsa-87-sample-message.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v6-mldsa-87-sample-signature.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v6-slhdsa-128s-sample-sk.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v6-slhdsa-128s-sample-pk.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v6-slhdsa-128s-sample-message.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v6-slhdsa-128s-sample-signature.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v6-slhdsa-128f-sample-sk.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v6-slhdsa-128f-sample-pk.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v6-slhdsa-128f-sample-signature.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v6-slhdsa-256s-sample-sk.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v6-slhdsa-256s-sample-pk.asc
draft-ietf-openpgp-pqc.xml: test-vectors/v6-slhdsa-256s-sample-signature.asc
